export const ADD_NEW_SERIAL = 'ADD_NEW_SERIAL'
export const GET_SERIALS = 'GET_SERIALS'
export const GET_CURRENT_SERIAL = 'GET_CURRENT_SERIAL'
export const PUT_CHANGE_USER = 'PUT_CHANGE_USER'
export const GET_USER = 'GET_USER'

export const INITIALIZING_APP = 'INITIALIZING_APP'