export const ADD_NEW_SERIAL = 'ADD_NEW_SERIAL'
export const GET_SERIALS = 'GET_SERIALS'
export const GET_CURRENT_SERIAL = 'GET_CURRENT_SERIAL'
export const PUT_CHANGE_RAITING = 'PUT_CHANGE_RAITING'
export const GET_USERS_SERIALS = 'GET_USERS_SERIALS'

export const INITIALIZING_APP = 'INITIALIZING_APP'